feat: add eslint-plugin-jest to backend template
Add eslint-plugin-jest to new backend plugins created by `npx backstage-cli new`.

When creating a new backstage plugin it prints an error as such:

```
    Error: Failed to load plugin 'jest' declared in '.eslintrc.js': Cannot find module 'eslint-plugin-jest'
    Require stack:
       - ...omitted.../plugin-backend/__placeholder__.js
       Referenced from: ...omitted.../plugin-backend/.eslintrc.js

    Warning: Failed to execute command yarn lint --fix

    🎉  Successfully created backend-plugin
```

This aims to fix that by including eslint-plugin-jest as a devDependency

Signed-off-by: Rickard Dybeck <dybeck@spotify.com>