techdocs-cli.js: remove -s yarn flag
I think this was removed in yarn v2?

with yarn 4.8.1 I get this:

```
❯ yarn techdocs-cli
Unknown Syntax Error: Unsupported option name ("-s").

$ yarn cache clean [--mirror] [--all]
$ yarn cache clean [--mirror] [--all]
$ yarn config get [--why] [--json] [--no-redacted] <name>
$ yarn config set [--json] [-H,--home] <name> <value>
$ yarn config unset [-H,--home] <name>
$ yarn set resolution <descriptor> <resolution>
$ yarn set version from sources [--path #0] [--repository #0] [--branch #0] [--plugin #0] [-n,--dry-run] [--no-minify] [-f,--force] [--skip-plugins]
$ yarn set version [--yarn-path] [--only-if-needed] <version>
$ yarn workspaces list [--since] [-R,--recursive] [--no-private] [-v,--verbose] [--json]
$ yarn --clipanion=definitions
$ yarn help
$ yarn help
$ yarn help
$ yarn <leadingArgument> ...
$ yarn -v
$ yarn -v
$ yarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
$ yarn bin [-v,--verbose] [--json] [name]
$ yarn config [--no-defaults] [--json] ...
$ yarn exec <commandName> ...
$ yarn explain peer-requirements [hash]
$ yarn explain [--json] [code]
$ yarn info [-A,--all] [-R,--recursive] [-X,--extra #0] [--cache] [--dependents] [--manifest] [--name-only] [--virtuals] [--json] ...
$ yarn install [--json] [--immutable] [--immutable-cache] [--refresh-lockfile] [--check-cache] [--check-resolutions] [--inline-builds] [--mode #0]
$ yarn install [--json] [--immutable] [--immutable-cache] [--refresh-lockfile] [--check-cache] [--check-resolutions] [--inline-builds] [--mode #0]
$ yarn link [-A,--all] [-p,--private] [-r,--relative] ...
$ yarn unlink [-A,--all] ...
$ yarn node ...
$ yarn plugin check [--json]
$ yarn plugin import from sources [--path #0] [--repository #0] [--branch #0] [--no-minify] [-f,--force] <name>
$ yarn plugin import [--checksum] <name>
$ yarn plugin remove <name>
$ yarn plugin list [--json]
$ yarn plugin runtime [--json]
$ yarn rebuild ...
$ yarn remove [-A,--all] [--mode #0] ...
$ yarn run [--json]
$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] [--require #0] <scriptName> ...
$ yarn up [-i,--interactive] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-R,--recursive] [--mode #0] ...
$ yarn why [-R,--recursive] [--json] [--peers] <package>
$ yarn workspace <workspaceName> <commandName> ...
$ yarn constraints query [--json] <query>
$ yarn constraints source [-v,--verbose]
$ yarn constraints [--fix] [--json]
$ yarn create [-p,--package #0] [-q,--quiet] <command> ...
$ yarn dlx [-p,--package #0] [-q,--quiet] <command> ...
$ yarn init [-p,--private] [-w,--workspace] [-i,--install] [-n,--name #0]
$ yarn init [-p,--private] [-w,--workspace] [-i,--install] [-n,--name #0] <initializer> ...
$ yarn search
$ yarn upgrade-interactive
$ yarn npm audit [-A,--all] [-R,--recursive] [--environment #0] [--json] [--no-deprecations] [--severity #0] [--exclude #0] [--ignore #0]
$ yarn npm info [-f,--fields #0] [--json] ...
$ yarn npm publish [--access #0] [--tag #0] [--tolerate-republish] [--otp #0]
$ yarn npm tag add <package> <tag>
$ yarn npm tag list [--json] [package]
$ yarn npm tag remove <package> <tag>
$ yarn pack [--install-if-needed] [-n,--dry-run] [--json] [-o,--out #0]
$ yarn patch [-u,--update] [--json] <package>
$ yarn unplug [-A,--all] [-R,--recursive] [--json] ...
$ yarn stage [-c,--commit] [-r,--reset] [-n,--dry-run]
$ yarn version apply [--all] [--dry-run] [--prerelease] [--exact] [-R,--recursive] [--json]
$ yarn version check [-i,--interactive]
$ yarn version [-d,--deferred] [-i,--immediate] <strategy>
$ yarn workspaces focus [--json] [--production] [-A,--all] ...
$ yarn workspaces foreach [--from #0] [-A,--all] [-R,--recursive] [-W,--worktree] [-v,--verbose] [-p,--parallel] [-i,--interlaced] [-j,--jobs #0] [-t,--topological] [--topological-dev] [--include #0] [--exclude #0] [--no-private] [--since] [-n,--dry-run] <commandName> ...
node:child_process:966
    throw err;
    ^

Error: Command failed: yarn -s workspace @techdocs/cli build
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at Object.<anonymous> (/Users/mattbrown/code/backstage/scripts/techdocs-cli.js:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 4320,
  stdout: null,
  stderr: null
}

Node.js v20.19.4
```

Signed-off-by: Matt Brown <mattbrown@spotify.com>