Trying to get a working Dockerfile for teh multistage build
Still stuck at this stage:

```
 > [build 15/17] RUN yarn tsc:
60.35 error TS2688: Cannot find type definition file for 'jest'.
60.35   The file is in the program because:
60.35     Entry point of type library 'jest' specified in compilerOptions
60.35 
60.35 error TS2688: Cannot find type definition file for 'webpack-env'.
60.35   The file is in the program because:
60.35     Entry point of type library 'webpack-env' specified in compilerOptions
```

I don't understand how this is supposed to work. Finding these node & yarn tricks to get past `yarn install --immutable`was so hard already....

Signed-off-by: nodje <coolnodje@gmail.com>